/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LoginPop {
        "appID": string;
        "appName": string;
    }
}
declare global {
    interface HTMLLoginPopElement extends Components.LoginPop, HTMLStencilElement {
    }
    var HTMLLoginPopElement: {
        prototype: HTMLLoginPopElement;
        new (): HTMLLoginPopElement;
    };
    interface HTMLElementTagNameMap {
        "login-pop": HTMLLoginPopElement;
    }
}
declare namespace LocalJSX {
    interface LoginPop {
        "appID"?: string;
        "appName"?: string;
    }
    interface IntrinsicElements {
        "login-pop": LoginPop;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "login-pop": LocalJSX.LoginPop & JSXBase.HTMLAttributes<HTMLLoginPopElement>;
        }
    }
}
