/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DropDownItems } from "./components/as-header/constant";
export { DropDownItems } from "./components/as-header/constant";
export namespace Components {
    interface AsHeader {
        "appTitle": string;
        "items": DropDownItems[];
        "logoutFunction": (event: PointerEvent) => void;
        "userName": string;
    }
}
declare global {
    interface HTMLAsHeaderElement extends Components.AsHeader, HTMLStencilElement {
    }
    var HTMLAsHeaderElement: {
        prototype: HTMLAsHeaderElement;
        new (): HTMLAsHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "as-header": HTMLAsHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AsHeader {
        "appTitle"?: string;
        "items"?: DropDownItems[];
        "logoutFunction"?: (event: PointerEvent) => void;
        "userName"?: string;
    }
    interface IntrinsicElements {
        "as-header": AsHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "as-header": LocalJSX.AsHeader & JSXBase.HTMLAttributes<HTMLAsHeaderElement>;
        }
    }
}
